name: Actions Workflow

on:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  run-github-actions:
      runs-on: ubuntu-latest
      steps:
        - name: List Directory
          run: |
            pwd
            ls -lrt
            ls -alrt
        - name: Checkout
          uses: actions/checkout@v1
        
        - name: List Directory after Checkout
          run: |
            pwd
            ls -lrt
            ls -alrt

        - name: Simple JS Actions
          id: greet
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: Joseph
        - name: Log Greeting Time
          run: echo "${{ steps.greet.outputs.time }}"