name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:14.21.2-alpine3.16
    steps:
      - name: Log Node Version
        run: |
          node -v
          cat /etc/os-release
