name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6, 8, 10]
      max-parallel: 2
      fail-fast: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: New Node Version
        run: node -v