name: Matrix
on: push

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6, 8, 10]
        include:
          - os: ubuntu-latest
            node_version: 6
            is_ubuntu_6: true
        exclude:
          - os: windows-latest
            node_version: 8
          - os: macos-latest
            node_version: 10

    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_6: ${{ matrix.is_ubuntu_6 }}
    steps:
      - name: Log Node Version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - name: New Node Version
        run: |
          node -v
          echo "IS_UBUNTU_6 variable : " $IS_UBUNTU_6